[msbsound]
title = "MSBSOUND ─ Album Special"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=444106&memberNo=838758"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
contentSelector = "a > div img[src]"

[78avenue]
title = "78Avenue ─ CLASS"
url = "http://78avenue.com/product/list.html?cate_no=42"
entrySelector = "ul li"
titleSelector = "div.description strong > a span:nth-child(2)"
linkSelector = "div.description strong a"
