[melon]
title = "멜론 티켓"
url = "https://ticket.melon.com/csoon/index.htm"
entrySelector = "div ul[class='list_ticket_cont'] li"
titleSelector = "a[class='tit']"
linkSelector = "a[class='tit']"
contentSelector = "span[class='date']"
waitUntil = "networkidle"

[interpark]
title = "인터파크 티켓"
url = "http://ticket.interpark.com/Webzine/Paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=0&stext=&KindOfGoods=&Genre=&sort="
entrySelector = "tbody > tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td[class='date']"
waitUntil = "networkidle"

[interpark_m]
title = "인터파크 티켓 모바일"
url = "http://mticket.interpark.com/Notice/"
entrySelector = "div[class='list'] div.item"
titleSelector = "p[class='label']"
linkSelector = "a"
contentSelector = "dl[class='ticketOpen'] > dd"
imageSelector = "span img"
waitUntil = "networkidle"

[yes24]
title = "예스24 티켓"
url = "http://ticket.yes24.com/New/Notice/NoticeMain.aspx"
entrySelector = " tbody tr:not(:first-child)"
titleSelector = "a > em"
linkSelector = "td:nth-child(2) > a"
contentSelector = "td:nth-child(3)"
waitUntil = "networkidle"

[yes24_m]
title = "예스24 티켓 모바일"
url = "http://m.ticket.yes24.com/Notice/List.aspx?type=1"
entrySelector = "#BoardList > li"
titleSelector = "a > div.brd_name.limit_2ln"
linkSelector = "a[class='lnk_brd']"
contentSelector = "em[class='txt']"
waitUntil = "networkidle"

[ticketlink]
title = "티켓링크"
url = "http://www.ticketlink.co.kr/help/notice"
entrySelector = "tbody[id='nTableBody'] tr"
titleSelector = "td.tl.p_reative > a"
linkSelector = "td a"
contentSelector = "td[class='open_info']"
waitForSelector = ".basic_tbl"

[ticketlink_m]
title = "티켓링크 모바일"
url = "http://m.ticketlink.co.kr/help/notice"
entrySelector = "#detail_content > li"
titleSelector = "h3"
linkSelector = "a"
contentSelector = "a > dl > dd:nth-child(2)"

[vlive]
title = "V LIVE"
url = "https://www.vlive.tv/home/video/more?pageNo=1&pageSize=50&viewType=recent&lang=ko"
entrySelector = "li[class^='video_list_cont _video']"
titleSelector = "a.video_tit"
linkSelector = "a"
imageSelector = "img"
contentSelector = "a[class='name']"

[musinsa]
title = "무신사 ─ 패션 뉴스"
url = "https://magazine.musinsa.com/?m=news"
entrySelector = "ul[class='news-article-list article-list list'] li[class='listItem']"
titleSelector = "p[class='title'] a"
linkSelector = "div.articleImg > a"
imageSelector = "div[class='articleImg'] a img"
contentSelector = "div[class='description'] a p"
waitUntil = "networkidle"

[kindiechart]
title = "K-INDIE CHART"
url = "http://mirrorballmusic.co.kr/k-indie-chart/"
entrySelector = "div[class='category-post-list'] article"
titleSelector = "h1[class='post-title blue']"
linkSelector = "div a[class='btn-view-chart']"
imageSelector = "div[class='post-thumb'] img"
contentSelector = "h2[class='sub-title']"
waitUntil = "networkidle"

