[interpark]
title = "인터파크 티켓"
url = "http://ticket.interpark.com/Webzine/Paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=0&stext=&KindOfGoods=&Genre=&sort="
entrySelector = "tbody > tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td[class='date']"
waitUntil = "networkidle"

[interpark_m]
title = "인터파크 티켓 모바일"
url = "http://mticket.interpark.com/Notice/"
entrySelector = "div[class='list'] div.item"
titleSelector = "p[class='label']"
linkSelector = "a"
contentSelector = "dl[class='ticketOpen'] > dd"
imageSelector = "span[class='img']"
waitUntil = "networkidle"

[ticketlink]
title = "티켓링크"
url = "http://m.ticketlink.co.kr/help/notice"
entrySelector = "#detail_content > li"
titleSelector = "h3"
linkSelector = "a"
contentSelector = "a > dl > dd:nth-child(2)"

[vlive]
title = "V LIVE"
url = "https://www.vlive.tv/home/video/more?pageNo=1&pageSize=50&viewType=recent&lang=ko"
entrySelector = "li[class^='video_list_cont _video']"
titleSelector = "a.video_tit"
linkSelector = "a"
imageSelector = "img"

[vlive_smtown]
title = "SMTOWN ─ Media Board"
url = "https://vlive.tv/channel/FD53B/board/3530"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_redvelvet]
title = "Red Velvet ─ Star Board"
url = "https://vlive.tv/channel/DCF447/board/4540"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_aespa_notice]
title = "aespa ─ Notice"
url = "https://vlive.tv/channel/97CCED/board/7374"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"
