[msbsound]
title = "MSBSOUND ─ Album Special"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=444106&memberNo=838758"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"

[78avenue]
title = "78Avenue ─ CLASS"
url = "http://78avenue.com/product/list.html?cate_no=42"
entrySelector = "div.xans-element-.xans-product.xans-product-normalpackage > div > ul"
titleSelector = "div.description strong > a span:nth-child(2)"
linkSelector = "div.description strong a"

[vlive]
title = "Star Board"
url = "https://vlive.tv/channel/E1F3A7/board/4386"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_loona]
title = "LOONA ─ Star Board"
url = "https://vlive.tv/channel/E1F3A7/board/4386"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_rv]
title = "Red Velvet ─ Star Board"
url = "https://vlive.tv/channel/DCF447/board/4540"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_aespa_notice]
title = "aespa ─ MY"
url = "https://www.vlive.tv/channel/97CCED/board/7375"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[vlive_smtown]
title = "SMTOWN ─ Media Board"
url = "https://www.vlive.tv/channel/FD53B/board/3530"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"

[geeknews]
title = "GeekNews"
url = "https://news.hada.io"
entrySelector = ".topic"
titleSelector = ".topictitle"
linkSelector = ".topictitle a"
